### ISSUE TITLE
Refactor AuthContext in API

### ISSUE THREAD

**Issue by muXxer** [iotaledger/wasp-legacy#1588]
Instead of setting the AuthContext in the context, we could simply pass it to the `ValidatePermissions` middleware.

**Comment by howjmay** [comment]
This may make the implementation become too complex, since we need to pass some information (e.g. permission) to the handler function.
Here is an example https://github.com/iotaledger/wasp/blob/develop/packages/webapi/controllers/users/user.go#L52
So keeping the current way may be better for me. Or there is some other way to do the refactor that I didn't think about
