### ISSUE TITLE
negative gas with `eth_getTransaction`

### ISSUE THREAD

**Issue by shufps** [iotaledger/wasp-legacy#2484]
A summary of the problem:

- we have a [tx](https://explorer.evm.testnet.shimmer.network/tx/0x510d1341bd7bb508247f2aba01d67039441b6b4ae7e8de044781259af98d701b/state) that reports a gas usage of `18,446,744,073,709,393,037`  and appears as success in blockscout

- `eth_getTransaction`  has that same odd gas usage: `0xfffffffffffd948d` , interestingly enough "cumulative gas" looks fine

- `debug_traceTransaction`  reports a normal gas value: `0x5a8b`

- the ISC receipt also reports a normal gas value:  `1000000`  but marks the tx as failed: `Error: execution reverted`

for reference this is the function called there:

https://docs.uniswap.org/contracts/v3/reference/periphery/NonfungiblePositionManager#increaseliquidity
https://docs.uniswap.org/contracts/v3/guides/providing-liquidity/increase-liquidity
(no ISC calls involved)

**Comment by MoonLabsDev** [comment]
happens on alot of transactions that all work on the same state when blockchain is congested. for example these hashes:

https://explorer.evm.testnet.shimmer.network/tx/0xbe139dee4bd89481a27ffcec68d4e4c7d82f7dae0bbd95357176c8ad8d928794
https://explorer.evm.testnet.shimmer.network/tx/0x89abd4657cc3861fdd51b4712c6217e1b1162bd5da117268f6ad65d4a6eb64d5
https://explorer.evm.testnet.shimmer.network/tx/0xf2757b89d87d39575df411be241759903f720d4005bb48b74924b6da3433ab82
https://explorer.evm.testnet.shimmer.network/tx/0x19ad23cca6909336ead80f6b4f12e89d0ec79d24323556ccf37bc652ea9ede87

They all want to execute a function on a contract with a counter that increments. Tx 1-3 all have negative gas, all show up as successful on explorer, but actually reverted. tx4 is successfull and has correct gas.  All generated events actually show the same counter value and no actual reason to fail.

Maybe they all worked on the same input state and all were successfull but consensus came to the conclusion that only 1 thing can be true and choose the last one and reverted the others, marked them as failed because of inconstistent state? there are over 713 similar cases that the IOTA Heroes Team found. 

If there are multiple transactions over multiple block that work on the same state, the last transaction is successfull and all others have the described negative gas, reverted but show as success.

IF they are in the same block, then the first Tx is sucessfull and the others have negative gas, show sucess, but actually reverted.

**Comment by jorgemmsilva** [comment]
https://github.com/iotaledger/wasp/pull/2525 should fix this. Let's re-open if the issue persists after the upcoming release
