### ISSUE TITLE
msg.value gives wrong value (Security issue)

### ISSUE THREAD

**Issue by MoonLabsDev** [iotaledger/wasp-legacy#3029]
To reproduce call the "test" function in the following contract with for example "4679500000000000".
on all other chains balance & received would have the same values afterwards... which is **4679**5**00000000000**
but actually received is **4679**0**00000000000**. Basicly msg.value is wrong and you cant rely on it. this opens up some attack vectors, makes msg.value complety unreliable and the only workaround would be to measure belance before and after to calculate the actually received amount OR to round msg.value after 6 decimals MANUALLY.

Both options mean that All smart contract developers that come from any other EVM, have to make big adjustments to their codebase to work on shimmer. 

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.9;

contract Test
{
    uint256 public received;
    uint256 public balance;

    function test() external payable
    {
        received = msg.value;
        balance = address(this).balance;
    }

    receive() external payable { }
}
```

**Comment by MoonLabsDev** [comment]
so why is that important? thankfully we have high gas price, otherwise....

1. you can call wSMR.deposit{ value: "999999999999" }()
2. you get 999999999999 wSMR
3. as SMR actually only got 6 decimals but you have to treat it as it has 18... the last 12 digits are ignored
4. you therefor pay 0 SMR but gain 999999999999 wSMR
5. in a theoretical scenario where you dont have gas costs, you could thereby mint free wSMR, without actually losing any SMR
6. you could rinse&repeat for infinite free wSMR that can then be unwrapped to SMR

yes this scenario doesnt work thanks to gas, but you can try it out and reproduce it and check the results... ignoring gas costs... you can "mint wSMR for free and when collected enough, unwrap to SMR again which would mint fee SMR for you" (actually i guess you would "steal" the SMR that is locked inside of the wSMR contract that was locked/wraped by others and you can can it by minting enough free wSMR)

quite sure there are other attack vectors in other contracts that rely on msg.value, so please find a good fix for it

**Comment by trungtt198x** [comment]
> so why is that important? thankfully we have high gas price, otherwise....
> 
> 1. you can call wSMR.deposit{ value: "999999999999" }()
> 2. you get 999999999999 wSMR
> 3. as SMR actually only got 6 decimals but you have to treat it as it has 18... the last 12 digits are ignored
> 4. you therefor pay 0 SMR but gain 999999999999 wSMR
> 5. in a theoretical scenario where you dont have gas costs, you could thereby mint free wSMR, without actually losing any SMR
> 6. you could rinse&repeat for infinite free wSMR that can then be unwrapped to SMR
> 
> yes this scenario doesnt work thanks to gas, but you can try it out and reproduce it and check the results... ignoring gas costs... you can "mint wSMR for free and when collected enough, unwrap to SMR again which would mint fee SMR for you" (actually i guess you would "steal" the SMR that is locked inside of the wSMR contract that was locked/wraped by others and you can can it by minting enough free wSMR)
> 
> quite sure there are other attack vectors in other contracts that rely on msg.value, so please find a good fix for it

I've performed again your deposit tx as below:
https://explorer.evm.testnet.shimmer.network/tx/0x939d3fd2aa9f4db5317a11729cadb7ae272247f2f10aee15722dc8a9c7ed9bf9

Native gas token `SMR` uses 6 decimals but the token `wSMR` contract uses 18 decimals.
Thus, the `deposit()` function receives the input argument with 18 decimals.
So, if you put in `999999999999` then it will be `0.000000999999999999 SMR` as the actual amount and eventually, you'll also get `0.000000999999999999 wSMR`. Quite correct.

To sum up, rounding does not happen on contract level. It happens only on dApps deciding how many decimals they prefer to display.

**Comment by MoonLabsDev** [comment]
meaning you pay nothing, but get free wSMR (after ignoring gas costs).

Again this is just an example of the effect, but the real issue is smart contracts can't rely on msg.value?
as you comment seem to make it sound like "this is no issue"

**Comment by trungtt198x** [comment]
> meaning you pay nothing, but get free wSMR (after ignoring gas costs).
> 
> Again this is just an example of the effect, but the real issue is smart contracts can't rely on msg.value? as you comment seem to make it sound like "this is no issue"

You cannot pay nothing. 
`999999999999` that is equivalent to `0.000000999999999999 SMR` will never be rounded to zero on the Solidity contract level. Like I said that, the rounding happens only on the dApps.

**Comment by MoonLabsDev** [comment]
then can you explain the behaviour i the first comment with the test contract i posted?

**Comment by MoonLabsDev** [comment]
received and balance should be same value but they arent. no dapp involved but your evm rounded. dont get stuck on the wSMR example

**Comment by MoonLabsDev** [comment]
> > meaning you pay nothing, but get free wSMR (after ignoring gas costs).
> > Again this is just an example of the effect, but the real issue is smart contracts can't rely on msg.value? as you comment seem to make it sound like "this is no issue"
> 
> You cannot pay nothing. `999999999999` that is equivalent to `0.000000999999999999 SMR` will never be rounded to zero on the Solidity contract level. Like I said that, the rounding happens only on the dApps.

again.... 

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.9;

contract Test
{
    uint256 public received;
    uint256 public balance;

    function test() external payable
    {
        received = msg.value;
        balance = address(this).balance;
    }

    receive() external payable { }
}
```

then use any number that would be "rounded to zero" so less than 1*10^12

the received variable will contain the value you used. but balance is 0. so nothing was payed or transfered. just try it out. stop talking about dApps.

![image](https://github.com/iotaledger/wasp/assets/103362189/61dc0ae5-3027-4f87-acd4-86e7e87a4962)
 how is this not proof? 

https://explorer.evm.shimmer.network/tx/0x8a1eda008d455b6e123da7387fae2b7b6df8f3b0a6a7a3308fcde20fb64780ec

btw I asked Security Reasearchers from AuditOne.... You "official partner" what they think about the bug and the strange beavior. their response:

_Regarding 1.: Can't come up with a really severe issue/exploit on the spot, but I'm sure this can lead to problems - even if it's just in corner cases. Will ponder this a bit...
Regarding 2.: 100%! And a poorly documented quirk! This behavior will be VERY counter-intuitive for devs coming from other protocols.
Regarding 3.: You already suggested some valid steps that smart contract devs can take to keep this issue under control. As far as I see it atm, the best fix would be to change SMR's decimals from 6 to 18 on the protocol level. However, as I already said, I don't really know the motivation behind picking 6 and potential technical constraints that ultimately led to this decision. Also, I'd assume it's a serious effort to go ahead and change the decimals on the protocol level. So, maybe a combination of baking rounding into msg.value + documenting this VERY well for new devs entering the ecosystem might be the way to go._

if you dont listen to me.... fine... but listen to security researcher and audit firms. Go check with AuditOne yourself

**Comment by marcobesier** [comment]
Hey, everyone, I'm chiming in here to emphasize the critical severity of this issue. Since a potential exploit is already mentioned above in plain sight, I'll drop it here, too.

The example I'll provide here is what @MoonLabsDev already described above, just expanded and hopefully even easier to reproduce for you:

While the (currently) low price of Shimmer makes it hard to exploit this issue for immediate profit, there is still a ton of damage one can do to ANY DeFi protocol on Shimmer - either "for the fun of it" or to ruin one or more competitor protocols. As a simple example, consider the following Wrapped Shimmer contract:

```
// SPDX-License-Identifier: UNLICENSE
pragma solidity 0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract WrappedShimmer is ERC20 {
    constructor() ERC20("Wrapped Shimmer", "WSMR") {}

    function deposit() external payable {
        _mint(msg.sender, msg.value);
    }

    function withdraw(uint256 amount) external {
        require(balanceOf(msg.sender) >= amount, "Insufficient balance");
        _burn(msg.sender, amount);
        (bool success, ) = msg.sender.call{value: amount}("");
        require(success, "Withdrawal failed");
    }

    function getBalance() external view returns (uint256) {
        return address(this).balance;
    } 
}
```
Further, suppose a user calls deposit() with a tx value of 1 glow (i.e., 1_000_000_000_000 wei).

If you now call balanceOf(user), it'll return 1_000_000_000_000. Correspondingly, if you call getBalance() to check the contract's balance, you'll get 1_000_000_000_000, too. In other words, nothing bad/unexpected happened so far.

**However, an attacker could now easily drain all the liquidity out of this protocol by doing the following:**

1. Make two calls to deposit() with tx values chosen such that the individual tx value is < 1_000_000_000_000, but their sum is >= 1_000_000_000_000 wei. E.g., call deposit() with a tx value of 0.5 glow (500_000_000_000 wei) twice. (More on that below.) This results in balanceOf(attacker) == 1_000_000_000_000, but will leave the balance of the contract unchanged (!!!) since the ShimmerEVM will truncate each of the attacker's transactions to have an actual value of 0. However, since the contract relies on msg.value for issuing its ERC20 tokens, it will register two deposits of 500_000_000_000 and accordingly mint 1_000_000_000_000 to the attacker.

2. The attacker can now call the withdraw function with amount == 1_000_000_000_000, and receive the corresponding payout.

NOTE: This would not work for amounts < 1 glow since msg.sender.call{value: amount}(""); would truncate the sent value to 0 (which, btw, is a completely unexpected quirk for developers coming from other EVM ecosystems and a separate, serious issue!). Therefore, the attacker needs to use at least two "print free money"-transactions to generate 1 glow worth of Wrapped Shimmer, so that she can deposit ERC20s that are at least worth 1 glow and get a corresponding payout through msg.sender.call{value: amount}("");

3. After the above steps, WE'RE LEFT WITH A CONTRACT BALANCE OF 0 ALTHOUGH THERE'S STILL WRAPPED ETHER IN CIRCULATION!!! I.e., the contract is no longer liquid and our user is no longer able to swap their Wrapped Shimmer with actual Shimmer.

**Again, notice that this is only a simple example to make the issue easy to reproduce in Remix. However, ANY smart contract protocol on the ShimmerEVM that's relying on msg.value for its internal bookkeeping (read: pretty much every single DeFi protocol) is vulnerable to such attacks - not just the Wrapped Shimmer contract mentioned above!** 

Hope this helps!

**Comment by fijter** [comment]
Thank you both for the extensive report and detailed explanations. We've looked into it with the team and can confirm the described behaviour is reproducible and undesired; However given this is only possible with the native asset (SMR) and only for amounts below 1 glow the practical impact of exploiting this is, as far as we can tell, very small. Like mentioned by @MoonLabsDev this is not practically abusable given the amount you will have to pay to do this in glow to pay for the gas to execute this is many times more than the extractable amount making it a big net loss to do so - The only thing you would achieve with such a thing is griefing and introducing a tiny amount of unbacked wrapped tokens (which is obviously not nice, but also not a major issue given we're talking about such a small amount just sending 1 wSMR to the burner address would compensate for over a million of those invocations). Yes, it can impact other contracts as well, but only for the native SMR asset and for less then 1 glow at a time with the same issues. 

Here is why this happens:

The native asset of the chain, SMR, only has 6 decimals on L1; Given L1 native assets are virtually represented in the Account module of ISC in a similar fashion it uses 6 decimals there as well. Given limitations on EVM level for the primary asset there are always 18 decimals for that, so we have to represent our 6 decimal L1 asset with 18 decimals there; This means that for the native asset the decimals beyond that 6th are ignored altogether, it's just padding. This behaviour has been there from the start and has been documented from the start in the ISC/Wasp dedicated EVM compatibility wiki page in a big red box: https://wiki.iota.org/wasp-evm/getting-started/compatibility/

When wrapping to wSMR, which has 18 decimals as requested by some projects to make it more compatible, you can indeed send less then 1 glow as the amount to the contract; The deduction of the native asset will be 0, and a fraction of a glow will be minted (unbacked) in the wSMR contract. If you do this a couple of time you can unwrap it again (very uneconomically given the gas fees) and get some SMR that was never there in the first place for your account, or it fails because the wSMR is partially unbacked and already empty (less likely given that would mean no one else would have any wSMR at that point any more). We obviously don't want a 99.999999% backed wSMR but a 100% backed wSMR, however the exploitable amount is so tiny and so expensive to increase while paying gas this is just not a very practical thing to do much harm with. The mentioned theoretical exploit when using a chain with no gas at all is possible; However also not very realistic since having a no fees smart contract chain is a unfeasible operation in the first place given it would be free and very easy then to DOS the chain with a infinite loop making this scenario only viable on a test chain with known actors interactions only, given zero fee chains simply doesn't work in the real world without being a easy target in the first place.

Nevertheless this is not something that we want obviously, no matter how small the amount sent should be the same as the amount received. As concluded above as well this does not only relate to the wSMR contract but to any contract using the native chain asset. We have been investigating how we want to tackle this and want to do some tests on the testnet soon rejecting excessive precision (this might bring incompatibilities with dApps though, also not desired), another option is to change the native asset logic which also has it's downsides. Once we've figured out what the best way forward is with this with the least amount of impact on the users and dApps we will update this ticket but a change like this needs a bit of time. A conclusion might be, if the alternatives bring more harm than do good, that this is a undesired property we'll have to live with because the alternatives are worse and we would need to document this behaviour better. 

I'm not sure if I'm missing something here, some edge case where this can have more impact, but as it stands with the examples above and the potential other cases I can think of the impact is small and I would not label something like this as a critical vulnerability, spreading potential unwarranted panic across the ecosystem for something that can not practically be abused with any severe impact. It was known from the start that ISC/Wasp's EVM implementation strives to be as compatible as possible with the existing EVM ecosystem but there will always be some exceptions; Which are known and documented.

**Comment by Finanzgoblin** [comment]
Lets say you were to call a generic function that uses msg.value and wSMR, using the ShimmerEVM, there would be a delta between the outputs a canonical EVM implementation as e.g. Ethereum / Binance Smart Chain. Check. 

However, by using other ERC-20 tokens, this possible attack vector does not exist? So the easiest way to mitigate the risk from a business perspective is initially disable wSMR due to the delta in decimals and the unexpected behavior that follows from it. 

So from my understanding, to pentest the SC properly, one would need to deploy it on two different testnets, ShimmerEVM and one that follows a canonical EVM implementation e.g. Goerli, do A/B testing, monitor the deltas in outputs and find attack vectors in the contracts that may be able to exploit the delta when calling msg.value.

I think the biggest issue here is not the technical implementation, but that Devs / dApps need to be aware that the IOTA EVM implementation has those deltas. Quite often, as seen with many rugdoc projects, developers often simply fork existing projects onto new EVMs and the business practice of quite a few degens is a simple hashcheck the contracts for being identical. The biggest issue will be the associated brand damage if a fully audited smart contract gets exploited due to the delta in outputs of msg.value.

**Comment by MoonLabsDev** [comment]
@fijter the best fix is to just round msg.sender on your EVM code to the decimals of the utilized token. i wont say "round to 6" as i guess for IOTA you want other ppl to be able to create their own sidechains and use their own token for gas maybe and they might have different decimals, so round it to decimals of that token.

Suire it is still strange that i send 1.23 and only receive 1.2... but as long as the receiving and gets the info that it received 1.2 and not 1.23 which is untrue... that this mitigates this problem ALOT.

Again this isnt even about attack vectors. this is about ensuring that you are COMPLIANT with solidity and EVM standards, to ensure that devs from other chains dont ahve to learn an extensive list of shimmer quirks and workarounds and adjust their bulletproof and audited contracts that work on any chain..... except shimmer (and other EVM sidechains on IOTA)

an simple

`msg.value = Math.round(msg.value, utilizedToken.decimals);`

or 

`msg.value = (msg.value / (10**(18 - utilizedToken.decimals)) * (10**(18 - utilizedToken.decimals);`

or anything similar would work. i guess as we talk about a BigNumber / BigInteger the Math.round wont really work, but first dividing by 10^(18-decimals) and then multiplying by it, will round it down as intended

**Comment by marcobesier** [comment]
@fijter Thanks for the extensive response! I agree that, since one can't turn a profit from this quirk (at least, not in a way we're currently aware of), it doesn't make sense to spread panic. This, btw, wasn't my intention at all. Just wanted to ensure this issue bubbles to the surface because it's a _very_ surprising quirk for someone coming from another ecosystem. As @Finanzgoblin mentioned, there certainly will be ppl who just "blindly" fork existing EVM projects from other chains onto Shimmer without caring much about Shimmer's docs and subtle quirks. 

I'll keep pondering this issue and will report back in case I stumble across a more severe consequence/exploit. 

One thing I will say, though, is that someone who's brand new to Shimmer and sees this quirk, will probably lose trust in the protocol and go build on something else because it seems too risky to build on something with such subtleties.

I can totally imagine that it must be super hard to balance all these different trade-offs properly. I'm curious: Why does L1 SMR have 6 decimals in the first place? Was it a more or less arbitrary choice, or are there some specific constraints that motivate that choice? Because it seems that the issues with msg.value, wsmr would disappear in a world where SMR's decimals would be 18 instead of 6...

**Comment by jorgemmsilva** [comment]
This has been fixed on the testnet and will be deployed onto ShimmerEVM soon.
