### ISSUE TITLE
Sending NFT from L2 to L1 gets stuck.

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wasp-legacy#3057]
**Describe the bug**
Sending an NFT from L2 to L1 often results in a transaction that is pending during at least 750s. We don't have this issue for native tokens or Shimmers or NFT L2 -> L2 Transactions. Retrying the same transaction results in `Tx already in mempool error`. If I wait for 750 sec, I get the following error message from the web3 provider: `Transaction was not mined within 750 seconds, please make sure 
your transaction was properly sent. Be aware that it might still be mined!`

**To Reproduce**

1. Use signed transaction you can find in the following txt file:
[signed-tx-nft-to-l2.txt](https://github.com/iotaledger/wasp/files/13283744/signed-tx-nft-to-l2.txt)
2. call `const receipt = provider?.eth.sendSignedTransaction(signedTransaction)`
3. See if receipt is passed back

Let me know if you need more singed tx or anything else!

**Expected behavior**
Transaction receipt is passed back or an error is thrown if it is not mineable.

**Network and versioning**
 - Type of L1 network: Shimmer Testnet
 - Type of Wasp chain: ShimmerEVM Testnet
 - Interaction method: JSON/RPC HTTP
 - Interaction software: web3js

**Comment by fijter** [comment]
It sounds a bit like the transactions are submitted using a wrong (too high maybe) nonce? It's impossible to see with the data provided. If a transaction is submitted with a too high nonce instead of the current one it stays in the mempool until it either times out or if the gap between current nonce and the next one is closed. It might be helpful to provide more information like a debug log and the exact transaction details you are submitting, if explicit nonces are provided, etc.

**Comment by Tuditi** [comment]
The nonce looks correct, because if I send any other L2 transaction with the same nonce, it goes through. Additionally, it also happens with 0x0 nonces. I created some new transactions here with the transaction data attached: 

[signed-tx-nft-to-l2.txt](https://github.com/iotaledger/wasp/files/13309643/signed-tx-nft-to-l2.txt)

**Comment by jorgemmsilva** [comment]
Should have been fixed by https://github.com/iotaledger/wasp/pull/3119 (live on testnet)

please re-open if not the case

**Comment by Tuditi** [comment]
Thanks for looking into it, it seems to be solved from our end!
