### ISSUE TITLE
Calling smart contract view functions via API causes panics when done in parallel 

### ISSUE THREAD

**Issue by lmoe** [iotaledger/wasp-legacy#382]
I'm using the current fairroulette contract as an example. 

To call a view function I'm using this URL:

`http://127.0.0.1:9090/chain/dTneb78gLtGVj4PiHQNPwUXXbkpqaxzMFmFCV3ZtwMcL/contract/df79d138/callview/roundNumber` [GET]

This should return a 200, with the following result: 
```
{"Items":[{"Key":"cm91bmROdW1iZXI=","Value":"AAAAAAAAAAA="}]}
```

If you request multiple view functions by doing sequential calls:
```
curl http://127.0.0.1:9090/chain/dTneb78gLtGVj4PiHQNPwUXXbkpqaxzMFmFCV3ZtwMcL/contract/df79d138/callview/roundNumber
curl http://127.0.0.1:9090/chain/dTneb78gLtGVj4PiHQNPwUXXbkpqaxzMFmFCV3ZtwMcL/contract/df79d138/callview/roundStatus
curl http://127.0.0.1:9090/chain/dTneb78gLtGVj4PiHQNPwUXXbkpqaxzMFmFCV3ZtwMcL/contract/df79d138/callview/fooBar
```

This works without issues.

Running them in parallel by using '&' at the end of the curl requests, seems to mix the responses in some way.
Sometimes the first response throws a `400 Bad Request`, while the second request is a `200 OK` but contains the data of response **1+2** like this:

```
{"Items":[{"Key":"cm91bmROdW1iZXI=","Value":"AAAAAAAAAAA="}, {"Key":"cm91bmRTdGF0dXM=","Value":"AAAAAAAAAAA="}]}
```

It appears to me that the execution is currently not thread safe. 

Further logging:

```
2021-09-08T12:07:00.732479952+02:00 127.0.0.1 GET /chain/pTwrRdxREzM12sMoSKaNirdnFWPrMjpiku8zFdTzniLr/contract/df79d138/callview/roundStatus 400 error="View call failed: go panicked"
2021-09-08T12:07:00.732576474+02:00 127.0.0.1 GET /chain/pTwrRdxREzM12sMoSKaNirdnFWPrMjpiku8zFdTzniLr/contract/df79d138/callview/roundNumber 400 error="View call failed: viewcontext: panic in VM: null.invalid key: 6"
2021-09-08T12:07:00.732655763+02:00 127.0.0.1 GET /chain/pTwrRdxREzM12sMoSKaNirdnFWPrMjpiku8zFdTzniLr/contract/df79d138/callview/roundStartedAt 400 error="View call failed: wasm trap: call stack exhausted\nwasm backtrace:\n  0: 0xffffffff - \u003cunknown\u003e!\u003cwasm function 144\u003e\n  1: 0x71ac - \u003cunknown\u003e!\u003cwasm function 91\u003e\n  2: 0x6642 - \u003cunknown\u003e!\u003cwasm function 64\u003e\n  3: 0x6f64 - \u003cunknown\u003e!\u003cwasm function 85\u003e\n  4: 0x786b - \u003cunknown\u003e!\u003cwasm function 116\u003e\n  5: 0x58b5 - \u003cunknown\u003e!\u003cwasm function 44\u003e\n"
2021-09-08T12:07:00.73293551+02:00 127.0.0.1 GET /chain/pTwrRdxREzM12sMoSKaNirdnFWPrMjpiku8zFdTzniLr/contract/df79d138/callview/lastWinningNumber 400 error="View call failed: wasm trap: call stack exhausted\nwasm backtrace:\n  0: 0xffffffff - \u003cunknown\u003e!\u003cwasm function 144\u003e\n  1: 0x71ac - \u003cunknown\u003e!\u003cwasm function 91\u003e\n  2: 0x6642 - \u003cunknown\u003e!\u003cwasm function 64\u003e\n  3: 0x6e31 - \u003cunknown\u003e!\u003cwasm function 82\u003e\n  4: 0x77f5 - \u003cunknown\u003e!\u003cwasm function 114\u003e\n  5: 0x58b5 - \u003cunknown\u003e!\u003cwasm function 44\u003e\n"

```

**Comment by dessaya** [comment]
I think this only happens with wasm contracts. @BugFreeSoftware is executing view calls in parallel supported by the wasm interpreter?

The following cluster test reproduces the issue. Replacing `go func` with just `func` makes it so that the view calls are sent in sequence and then the test passes.

```go
func TestSpamCallViewWasm(t *testing.T) {
	testutil.SkipHeavy(t)
	clu := newCluster(t)
	committee := []int{0}
	quorum := uint16(1)
	addr, err := clu.RunDKG(committee, quorum)
	require.NoError(t, err)
	chain, err := clu.DeployChain("chain", clu.Config.AllNodes(), committee, quorum, addr)
	require.NoError(t, err)

	e := &env{t: t, clu: clu}
	chEnv := &chainEnv{
		env:   e,
		chain: chain,
	}

	chEnv.requestFunds(scOwnerAddr, "client")
	chEnv.deployContract("inccounter", "inccounter sc", nil)

	{
		// increment counter once
		entryPoint := iscp.Hn("increment")
		tx, err := chEnv.chainClient().Post1Request(incHname, entryPoint)
		require.NoError(t, err)
		err = chain.CommitteeMultiClient().WaitUntilAllRequestsProcessed(chain.ChainID, tx, 30*time.Second)
		require.NoError(t, err)
	}

	const n = 1000
	ch := make(chan error, n)

	for i := 0; i < n; i++ {
		go func(i int) {
			cl := chain.SCClient(iscp.Hn("inccounter"), nil)
			r, err := cl.CallView("getCounter", nil)
			if err != nil {
				ch <- err
				return
			}

			v, ok, err := codec.DecodeInt64(r.MustGet(inccounter.VarCounter))
			if err != nil {
			} else if !ok {
				err = errors.New("!ok")
			} else if v != 1 {
				err = errors.New("v != 1")
			}
			ch <- err
		}(i)
	}

	for i := 0; i < n; i++ {
		err := <-ch
		if err != nil {
			t.Error(err)
		}
	}
}
```

**Comment by dessaya** [comment]
Adding a mutex in `WasmProcessor::call()` fixes the panics:

```go
type WasmProcessor struct {
	...
	mu        sync.Mutex
}

func (host *WasmProcessor) call(ctx iscp.Sandbox, ctxView iscp.SandboxView) (dict.Dict, error) {
	host.mu.Lock()
	defer host.mu.Unlock()
	...
}
```

(But of course this is not the correct solution, we need to be able to run view calls in parallel).

**Comment by BugFreeSoftware** [comment]
I've been thinking about this and I don't think this is possible with the current Wasm VM. The assumption with Wasm is currently: no threading, because it runs deterministic code. We load our Wasm SC code in an instance of the Wasm runtime and there it runs in isolation from other Wasm SCs. These separate instances can completely run in parallel. They have no way to interfere with each other at Wasm level, and this parallelization is supported by the Wasm runtime (WasmTime/Wasmer/etc).
But how does this work when a state update comes in while view calls are running already? That could seriously affect the results of the view calls, when the state is updated halfway the call. Or do we have a separate state copy from which the views are taking their data, which cannot change until all views are done? Also, even though the Wasm SCs run in separate VM instances, ultimately they share state because the entire chain has only a single state. Which means that calls to core contracts can be made in parallel from those SCs and potentially impact each other unless that is properly synchronized.

**Comment by lmoe** [comment]
I don't have so much knowledge about the deeper logic there, but one thing that comes to mind is, 
that the events inside the contract don't get emitted right at the call, but rather after the sc function has ended. 

Maybe it's enough to copy the state into some other location which the callview api call then accesses? 
Then these values would only change after each function has ended, which would be fine - at least for my use case.

Kind of like the same behavior with the events. But that doesn't solve the last issue Eric said then.

Maybe we could add something like an "uncertain state"?

**Comment by dessaya** [comment]
@BugFreeSoftware the protection from state updates is already in place, in the form of an optimistic reader. Whenever the state is read during the view call, if it has changed the optimistic reader will panic, and then the whole view call will be retried. See `packages/webapi/webapiutil/callview.go`.

To make it work with wasm, one idea is to have a pool of instances of wasm interpreters, and in `WasmProcessor::Call()` take a free interpreter from the pool, use it to run the code, then return it to the pool. Would something like this work?

**Comment by BugFreeSoftware** [comment]
I have been thinking about that and we can probably do better. It's not the code that is the problem but the code re-entrancy. We already save the memory state after initialization is done, and restore it before every function call. Because it needs the data from the initialization but after that it should be completely deterministic. I'm going to figure out if it is possible to call functions in parallel on the Wasm VM by giving each function call their own memory upon calling. It could be we are reusing the same memory block for every call and then parallel calls become an issue. But if each call has its own memory that should not be an issue. After that it's only a matter of verifying that the interface to ISCP is re-entrant as well and does not rely on any state. I thought I removed all of those but I may have missed one. Will investigate.

**Comment by BugFreeSoftware** [comment]
> Adding a mutex in `WasmProcessor::call()` fixes the panics:

No it doesn't. It will block any recursive call. Several tests will hang indefinitely.

**Comment by lmoe** [comment]
What did work was to put the mutex here: https://github.com/iotaledger/wasp/blob/roulette_poc/packages/webapi/webapiutil/callview.go#L17

Its not great but at least for the web api, it seems to make it work at the end. 
I believe `NewFromChain` is not threadsafe at some point. As putting the Mutex somewhere below brings up issues again.. 
Maybe we are referencing some data structure instead of copying it?

**Comment by BugFreeSoftware** [comment]
Fixed the problem for now. Mutex per SC processor. Can handle nested calls now. We can have multiple different SCs running in parallel because they each use a different processor. This should fix our problem for now until I can get multiple instances per processor running.
@lmoe please can you try to reproduce the WasmTime crash again with this code to see if this fixes that one for now?
